### ISSUE TITLE
请问云函数怎么部署呢

### ISSUE THREAD

**Issue by bestRenekton** [o2team/taro-ebook-source#10]
现在我clone了项目下来，然后npm run dev:weapp跑项目，然后用开发者工具带入dist项目，同时修改成了自己的appid，然后点击云开发，开通之后获得环境id，然后修改cloud里面所有的appid和环境id为自己的。请问接下来该怎么做呢，怎么部署那些函数

**Comment by Bless-L** [comment]
在微信开发工具里直接右键部署，详情可以看文档。https://developers.weixin.qq.com/miniprogram/dev/wxcloud/guide/functions/ide.html

**Comment by bestRenekton** [comment]
官网讲的很详细 谢谢
