### ISSUE TITLE
[taro-demo /client ]  regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by taorujun** [o2team/taro-ebook-source#6]
sdk uncaught third Error 
 regeneratorRuntime is not defined 
 ReferenceError: regeneratorRuntime is not defined
    at http://127.0.0.1:44655/appservice/utils/util.js:6:46
    at http://127.0.0.1:44655/appservice/utils/util.js:49:2
    at require (http://127.0.0.1:44655/appservice/__dev__/WAService.js:1:723572)
    at http://127.0.0.1:44655/appservice/__dev__/WAService.js:1:723181
    at http://127.0.0.1:44655/appservice/reducers/balance.js:23:13
    at require (http://127.0.0.1:44655/appservice/__dev__/WAService.js:1:723572)
    at http://127.0.0.1:44655/appservice/__dev__/WAService.js:1:723181
    at http://127.0.0.1:44655/appservice/reducers/index.js:29:16
    at require (http://127.0.0.1:44655/appservice/__dev__/WAService.js:1:723572)
    at http://127.0.0.1:44655/appservice/__dev__/WAService.js:1:723181

**Comment by Bless-L** [comment]
有没有开启ES6转ES5，有得话关闭它。同时重新npm install一下。
